name: build-node

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        default: '16'


jobs:
  build:
    runs-on: self-hosted
    envi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
      - run: npm install
      - run: npm run lint
      - run: npm run jest:ci
      - uses: actions/upload-artifact@v2
        with:
          name: jest-results
          retention-days: 1
          path: |
            test-report-sonar.xml
            coverage
