name: build-node

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        default: '16'
    secrets:
      NPM_HOST:
        required: true
      NPM_SCOPE:
        required: true
      NPM_TOKEN:
        required: true
jobs:
  node:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
      - run: echo //${{ secrets.NPM_HOST }}/:_authToken="${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: echo ${{ secrets.NPM_SCOPE }}:registry=https://${{ secrets.NPM_HOST }} >> ~/.npmrc
      - run: npm install
      - run: npm run lint
      - run: npm run jest:ci
      - run: OLD_PATH=$(pwd)
      - run: sed -i 's|'"$OLD_PATH"'|--PATH_PLACEHOLDER--|g' test-report-sonar.xml
      - run: cat test-report-sonar.xml
      - uses: actions/upload-artifact@v2
        with:
          name: jest-results
          retention-days: 1
          path: |
            test-report-sonar.xml
            coverage
