name: build-node

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        default: "16"
      folder:
        type: string
        default: "./"
      testCmd:
        type: string
        default: "jest:ci"
      buildCmd:
        type: string
        required: false
      buildOutputUploadPath:
        type: string
        required: false
      force:
        type: boolean
        default: false
    secrets:
      NPM_HOST:
        required: true
      NPM_SCOPE:
        required: true
      NPM_TOKEN:
        required: true
jobs:
  node:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ inputs.folder }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
      - name: login to verdaccio
        run: |
          echo //${{ secrets.NPM_HOST }}/:_authToken="${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo ${{ secrets.NPM_SCOPE }}:registry=https://${{ secrets.NPM_HOST }} >> ~/.npmrc
      - name: install
        if: inputs.force == false
        run: npm install
      - name: install
        if: inputs.force == true
        run: npm install --force
      - name: lint
        run: npm run lint
      - name: test
        run: npm run ${{ inputs.testCmd }}
      - name: prep reports
        run: |
          echo "Current old path is: $(pwd)"
          echo "OLD_PATH=$(pwd | sed 's,/,\\/,g')" >> $GITHUB_ENV
          export OLD_PATH=$(pwd)
          cat test-report-sonar.xml | awk -v OLD_PATH="$OLD_PATH/" -v PH="" '{sub(OLD_PATH, PH, $0); print $0}' > tmp && mv tmp test-report-sonar.xml
          cat test-report-sonar.xml
      - uses: actions/upload-artifact@v2
        with:
          name: jest-results
          retention-days: 1
          path: |
            ${{ inputs.folder }}test-report-sonar.xml
            ${{ inputs.folder }}coverage
      - name: build
        if: inputs.buildCmd
        run: npm run ${{ inputs.buildCmd }}
        env:
          CI: ""
      - name: upload build results
        if: inputs.buildOutputUploadPath
        uses: actions/upload-artifact@v2
        with:
          name: build-results
          retention-days: 1
          path: |
            ${{ inputs.folder }}${{ inputs.buildOutputUploadPath }}
