name: check-version-on-registry.yml

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      version-to-check:
        required: true
        type: string
      registry:
        required: false
        type: string
        default: registry.goresponsa.com
      registry-project:
        required: false
        type: string
        default: main
    secrets:
      RESPONSA_REGISTRY_USERNAME:
        required: true
      RESPONSA_REGISTRY_PASSWORD:
        required: true
    outputs:
      already-present:
        description: Returns 1 if package is already present in registry with input name and version
        value: ${{ jobs.version-checking.outputs.already-present }}

jobs:
  version-checking:
    runs-on: ubuntu-latest
    outputs:
        already-present: ${{ steps.registry-check.outputs.already-present }}
    steps:
      - name: Checking registry for image ${{ inputs.image-name }} and version ${{ inputs.version-to-check}}
        id: registry-check
        run: |
          export REG_PWD='${{ secrets.RESPONSA_REGISTRY_PASSWORD }}'
          manifest=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.RESPONSA_REGISTRY_USERNAME }}:${REG_PWD}" https://${{ inputs.registry }}/v2/${{ inputs.registry-project }}/${{ inputs.image-name }}/manifests/${{ inputs.version-to-check }})
          echo "already-present=$([[ ${manifest} -eq 200 ]] && { echo 1;:; } || { echo 0; })" >> $GITHUB_OUTPUT